using System.Text.Json;
using System.Text.Json.Serialization;
using Full.NET.Abstractions.Results;
using Full.NET.Modules.Identity.Contracts;

namespace Full.NET.Modules.Identity.Serialization;

[JsonSourceGenerationOptions(JsonSerializerDefaults.Web)]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(TokenResponse))]
[JsonSerializable(typeof(CurrentUserResponse))]
[JsonSerializable(typeof(UpdateLocaleRequest))]
[JsonSerializable(typeof(LocalePreferenceResponse))]
[JsonSerializable(typeof(NavigationNodeResponse[]))]
[JsonSerializable(typeof(AuthorizationTreeModuleResponse[]))]
[JsonSerializable(typeof(AuthorizationTreePageResponse[]))]
[JsonSerializable(typeof(AuthorizationTreeActionResponse))]
[JsonSerializable(typeof(TenantContextTokenResponse))]
[JsonSerializable(typeof(GrantSuperAdministratorRequest))]
[JsonSerializable(typeof(RevokeSuperAdministratorRequest))]
[JsonSerializable(typeof(BeginTotpEnrollmentResponse))]
[JsonSerializable(typeof(ConfirmTotpEnrollmentRequest))]
[JsonSerializable(typeof(TotpEnrollmentStatusResponse))]
[JsonSerializable(typeof(SuperAdministratorResponse[]))]
[JsonSerializable(typeof(SuperAdministratorAuditResponse[]))]
[JsonSerializable(typeof(SuperAdministratorChangeResponse))]
[JsonSerializable(typeof(CreateHostUserRequest))]
[JsonSerializable(typeof(UpdateHostUserRequest))]
[JsonSerializable(typeof(ResetHostUserPasswordRequest))]
[JsonSerializable(typeof(ImportHostUsersRequest))]
[JsonSerializable(typeof(ImportHostUsersResponse))]
[JsonSerializable(typeof(ImportHostUserRowResult))]
[JsonSerializable(typeof(ImportHostUserRowResult[]))]
[JsonSerializable(typeof(CreateHostUserRequest[]))]
[JsonSerializable(typeof(BatchHostUserIdsRequest))]
[JsonSerializable(typeof(BatchHostUserStatusResponse))]
[JsonSerializable(typeof(BatchHostUserStatusItem))]
[JsonSerializable(typeof(Guid[]))]
[JsonSerializable(typeof(HostUserResponse))]
[JsonSerializable(typeof(HostUserProjectedFieldsResponse))]
[JsonSerializable(typeof(PagedResult<HostUserResponse>))]
[JsonSerializable(typeof(HostUserRolesResponse))]
[JsonSerializable(typeof(ReplaceHostUserRolesRequest))]
[JsonSerializable(typeof(CreateHostRoleRequest))]
[JsonSerializable(typeof(UpdateHostRoleRequest))]
[JsonSerializable(typeof(ReplaceHostRolePermissionsRequest))]
[JsonSerializable(typeof(HostRoleResponse))]
[JsonSerializable(typeof(PagedResult<HostRoleResponse>))]
[JsonSerializable(typeof(HostRoleDataScopeResponse))]
[JsonSerializable(typeof(UpdateHostRoleDataScopeRequest))]
[JsonSerializable(typeof(FieldProjectionFieldDefinition))]
[JsonSerializable(typeof(FieldProjectionResourceDefinition))]
[JsonSerializable(typeof(FieldProjectionResourceDefinition[]))]
[JsonSerializable(typeof(ReplaceHostRoleFieldGrantsRequest))]
[JsonSerializable(typeof(HostRoleFieldGrantsResponse))]
[JsonSerializable(typeof(CreateHostMenuRequest))]
[JsonSerializable(typeof(UpdateHostMenuRequest))]
[JsonSerializable(typeof(HostMenuResponse))]
[JsonSerializable(typeof(PagedResult<HostMenuResponse>))]
[JsonSerializable(typeof(HostMenuResponse[]))]
[JsonSerializable(typeof(HostNavigationCatalogSyncResponse))]
[JsonSerializable(typeof(HostOnlineSessionResponse))]
[JsonSerializable(typeof(PagedResult<HostOnlineSessionResponse>))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(CreateHostApiKeyRequest))]
[JsonSerializable(typeof(CreateHostApiKeyResponse))]
[JsonSerializable(typeof(HostApiKeyResponse))]
[JsonSerializable(typeof(PagedResult<HostApiKeyResponse>))]
[JsonSerializable(typeof(HostDashboardSummaryResponse))]
[JsonSerializable(typeof(HostDashboardActivityResponse))]
[JsonSerializable(typeof(ModuleCatalogEntryResponse))]
[JsonSerializable(typeof(ModuleCatalogEntryResponse[]))]
[JsonSerializable(typeof(IReadOnlyList<ModuleCatalogEntryResponse>))]
[JsonSerializable(typeof(ReconcileOrganizationUnitProjectionRequest))]
[JsonSerializable(typeof(ReconcileOrganizationUnitProjectionResponse))]
internal partial class IdentityJsonSerializerContext : JsonSerializerContext;
