<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <RootNamespace>App.Host.Api</RootNamespace>
    <AssemblyName>App.Host.Api</AssemblyName>
    <FullNetPublishMode>Jit</FullNetPublishMode>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../../framework/fullnet/src/Hosts/Full.NET.Host.Api/Full.NET.Host.Api.csproj" />
  </ItemGroup>

</Project>