<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Full.NET.Data.Abstractions\Full.NET.Data.Abstractions.csproj" />
    <ProjectReference Include="..\Full.NET.Data.MySql\Full.NET.Data.MySql.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="dbup-core" />
    <PackageReference Include="dbup-mysql" />
    <PackageReference Include="dbup-sqlserver" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Migrations\**\*.sql" />
  </ItemGroup>

</Project>
