import assert from 'node:assert/strict';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import { prepareApplicationCrudVue } from './support/application-crud-vue.mjs';

function fixture(action) {
  const appRoot = mkdtempSync(join(tmpdir(), 'fullnet-business-vue-'));
  const put = (path, content) => {
    const destination = join(appRoot, path);
    mkdirSync(join(destination, '..'), { recursive: true });
    writeFileSync(destination, content);
  };
  try {
    put('packages/client-contracts/src/index.ts', 'export { createHttpClient } from \'./http.js\';\n');
    for (const name of ['guards.generated.ts', 'index.generated.ts', 'models.generated.ts', 'operations.generated.ts']) {
      put(`verification/ClientGeneration/generated/${name}`, `// application ${name}\n`);
    }
    put('clients/vue/products-page.generated.ts', '// generated page\n');
    put('clients/vue/products.generated.ts', '// generated adapter\n');
    put('clients/vue/productsView.vue', '<template><div>Product</div></template>\n');
    put('verification/CrudGeneration/module-target.json', JSON.stringify({ moduleName: 'Catalog', vueRouterPath: 'ui/admin/src/router/index.ts' }));
    put('ui/admin/src/router/index.ts', 'routes: [\n  { path: \'/403\', component: loadStatusView }\n]\n');
    return action({ appRoot, put });
  } finally { rmSync(appRoot, { recursive: true, force: true }); }
}

test('application Vue adoption exports only product operations and preserves generated bytes', () => fixture(({ appRoot }) => {
  const result = prepareApplicationCrudVue(appRoot);
  assert.deepEqual(result, { clientFiles: 4, vueFiles: 3, routePath: '/catalog/products' });
  const source = 'verification/ClientGeneration/generated/operations.generated.ts';
  const destination = 'packages/client-contracts/src/application-generated/catalog-product/operations.generated.ts';
  assert.deepEqual(readFileSync(join(appRoot, destination)), readFileSync(join(appRoot, source)));
  assert.ok(readFileSync(join(appRoot, 'packages/client-contracts/src/index.ts'), 'utf8')
    .startsWith('export { createHttpClient } from \'./http.js\';\n'), 'existing client exports changed');
  assert.match(readFileSync(join(appRoot, 'packages/client-contracts/src/index.ts'), 'utf8'),
    /catalogCreateProduct.*application-generated\/catalog-product\/operations\.generated\.js/su);
  assert.equal(readFileSync(join(appRoot, 'ui/admin/src/views/CatalogProductsView.vue'), 'utf8'),
    '<template><div>Product</div></template>\n');
  const target = JSON.parse(readFileSync(join(appRoot, 'verification/CrudGeneration/vue-target.json'), 'utf8'));
  assert.deepEqual(target.clientRoute, { routePath: '/catalog/products', vueRouteName: 'catalog-products',
    vueComponentPath: 'ui/admin/src/views/CatalogProductsView.vue' });
  assert.equal(existsSync(join(appRoot, 'ui/admin-layui')), false);
}));

test('application Vue adoption rejects occupied output before changing the client entry', () => fixture(({ appRoot, put }) => {
  put('ui/admin/src/views/CatalogProductsView.vue', '<template>Manual</template>');
  const index = readFileSync(join(appRoot, 'packages/client-contracts/src/index.ts'));
  assert.throws(() => prepareApplicationCrudVue(appRoot), /unused application path/u);
  assert.deepEqual(readFileSync(join(appRoot, 'packages/client-contracts/src/index.ts')), index);
  assert.equal(existsSync(join(appRoot, 'verification/CrudGeneration/vue-target.json')), false);
}));
