import assert from 'node:assert/strict';
import { existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import test from 'node:test';
import * as crudVue from './support/application-crud-vue.mjs';
import { CRUD_ARTIFACTS } from './support/application-crud-generation.mjs';

const { prepareApplicationCrudVue } = crudVue;

function fixture(action) {
  const appRoot = mkdtempSync(join(tmpdir(), 'fullnet-business-vue-'));
  const put = (path, content) => {
    const destination = join(appRoot, path);
    mkdirSync(join(destination, '..'), { recursive: true });
    writeFileSync(destination, content);
  };
  try {
    put('packages/client-contracts/src/index.ts', 'export { createHttpClient } from \'./http.js\';\n');
    put('packages/client-contracts/src/navigation-catalog.ts', "export const ADMIN_NAVIGATION_CATALOG = [\n  { componentKey: 'layout', routeName: 'layout', path: '/' }\n] as const;\n");
    for (const name of ['guards.generated.ts', 'index.generated.ts', 'models.generated.ts', 'operations.generated.ts']) {
      put(`verification/ClientGeneration/generated/${name}`, `// application ${name}\n`);
    }
    put('clients/vue/products-page.generated.ts', '// generated page\n');
    put('clients/vue/products.generated.ts', '// generated adapter\n');
    put('clients/vue/productsView.vue', '<template><div>Product</div></template>\n');
    put('verification/CrudGeneration/module-target.json', JSON.stringify({ moduleName: 'Catalog', vueRouterPath: 'ui/admin/src/router/index.ts' }));
    put('ui/admin/src/router/index.ts', 'routes: [\n  { path: \'/403\', component: loadStatusView }\n]\n');
    return action({ appRoot, put });
  } finally { rmSync(appRoot, { recursive: true, force: true }); }
}

test('application Vue adoption exports only product operations and preserves generated bytes', () => fixture(({ appRoot }) => {
  const result = prepareApplicationCrudVue(appRoot);
  assert.deepEqual(result, { clientFiles: 4, vueFiles: 3, routePath: '/catalog/products', navigationRegistered: true });
  const source = 'verification/ClientGeneration/generated/operations.generated.ts';
  const destination = 'packages/client-contracts/src/application-generated/catalog-product/operations.generated.ts';
  assert.deepEqual(readFileSync(join(appRoot, destination)), readFileSync(join(appRoot, source)));
  assert.ok(readFileSync(join(appRoot, 'packages/client-contracts/src/index.ts'), 'utf8')
    .startsWith('export { createHttpClient } from \'./http.js\';\n'), 'existing client exports changed');
  assert.match(readFileSync(join(appRoot, 'packages/client-contracts/src/index.ts'), 'utf8'),
    /catalogCreateProduct.*application-generated\/catalog-product\/operations\.generated\.js/su);
  assert.equal(readFileSync(join(appRoot, 'ui/admin/src/views/CatalogProductsView.vue'), 'utf8'),
    '<template><div>Product</div></template>\n');
  const target = JSON.parse(readFileSync(join(appRoot, 'verification/CrudGeneration/vue-target.json'), 'utf8'));
  assert.deepEqual(target.clientRoute, { routePath: '/catalog/products', vueRouteName: 'm7-catalog-products',
    vueComponentPath: 'ui/admin/src/views/CatalogProductsView.vue' });
  assert.match(readFileSync(join(appRoot, 'packages/client-contracts/src/navigation-catalog.ts'), 'utf8'),
    /componentKey: 'layout'.*\},\n  \{ componentKey: 'm7-catalog-products', routeName: 'm7-catalog-products', path: '\/catalog\/products'/su);
  assert.equal(existsSync(join(appRoot, 'ui/admin-layui')), false);
}));

test('application Vue adoption rejects occupied output before changing the client entry', () => fixture(({ appRoot, put }) => {
  put('ui/admin/src/views/CatalogProductsView.vue', '<template>Manual</template>');
  const index = readFileSync(join(appRoot, 'packages/client-contracts/src/index.ts'));
  assert.throws(() => prepareApplicationCrudVue(appRoot), /unused application path/u);
  assert.deepEqual(readFileSync(join(appRoot, 'packages/client-contracts/src/index.ts')), index);
  assert.equal(existsSync(join(appRoot, 'verification/CrudGeneration/vue-target.json')), false);
}));

test('application Vue adoption rejects a conflicting navigation key before copying files', () => fixture(({ appRoot, put }) => {
  put('packages/client-contracts/src/navigation-catalog.ts', 'export const ADMIN_NAVIGATION_CATALOG = [\n  { componentKey : "m7-catalog-products", routeName: "other", path: "/other" }\n] as const;\n');
  const index = readFileSync(join(appRoot, 'packages/client-contracts/src/index.ts'));
  assert.throws(() => prepareApplicationCrudVue(appRoot), /navigation key is already occupied/u);
  assert.deepEqual(readFileSync(join(appRoot, 'packages/client-contracts/src/index.ts')), index);
  assert.equal(existsSync(join(appRoot, 'ui/admin/src/views/CatalogProductsView.vue')), false);
}));

test('application Vue adoption rejects a conflicting route name before copying files', () => fixture(({ appRoot, put }) => {
  put('packages/client-contracts/src/navigation-catalog.ts', "export const ADMIN_NAVIGATION_CATALOG = [\n  { componentKey: 'other', routeName: 'm7-catalog-products', path: '/other' }\n] as const;\n");
  assert.throws(() => prepareApplicationCrudVue(appRoot), /navigation key is already occupied/u);
  assert.equal(existsSync(join(appRoot, 'ui/admin/src/views/CatalogProductsView.vue')), false);
}));

test('application Vue adoption rejects quoted navigation properties before copying files', () => fixture(({ appRoot, put }) => {
  put('packages/client-contracts/src/navigation-catalog.ts', "export const ADMIN_NAVIGATION_CATALOG = [\n  { 'componentKey': 'm7-catalog-products', 'routeName': 'other', 'path': '/other' }\n] as const;\n");
  assert.throws(() => prepareApplicationCrudVue(appRoot), /navigation catalog entry must use static fields/u);
  assert.equal(existsSync(join(appRoot, 'ui/admin/src/views/CatalogProductsView.vue')), false);
}));

test('application Vue adoption accepts the shipped navigation catalog shape', () => fixture(({ appRoot, put }) => {
  put('packages/client-contracts/src/navigation-catalog.ts',
    readFileSync(new URL('../../packages/client-contracts/src/navigation-catalog.ts', import.meta.url)));
  const result = prepareApplicationCrudVue(appRoot);
  assert.equal(result.navigationRegistered, true);
}));

test('application Vue regeneration preserves adopted edits and rejects generated source drift', () => fixture(({ appRoot, put }) => {
  put('clients/vue/productsView.vue', '<script setup lang="ts">\n</script>\n<template><div>Product</div></template>\n');
  prepareApplicationCrudVue(appRoot);
  for (const path of CRUD_ARTIFACTS) {
    if (!existsSync(join(appRoot, path))) put(path, `// generated ${path}\n`);
  }
  put('.fullnet/codegeneration-manifest.json', '{}');
  const source = readFileSync(join(appRoot, 'clients/vue/productsView.vue'));
  const calls = [];
  const run = (command, args, options) => {
    calls.push({ command, args, options });
    return calls.length === 1
      ? { status: 0, stdout: CRUD_ARTIFACTS.map(path => `Unchanged ${path}`).join('\n'), stderr: '' }
      : { status: 2, stdout: 'Conflict clients/vue/productsView.vue\n', stderr: '' };
  };
  const result = crudVue.verifyApplicationCrudVueRegeneration(appRoot,
    { reportDirectory: join(appRoot, 'evidence'), run });
  assert.deepEqual(result, { repeatUnchanged: true, manualPreserved: true, conflictRejected: true });
  assert.equal(calls.length, 2);
  assert.ok(calls.every(({ command, args, options }) => command === 'dotnet'
    && args[0] === 'exec' && args.includes('--apply') && options.cwd === appRoot));
  assert.deepEqual(readFileSync(join(appRoot, 'clients/vue/productsView.vue')), source);
  assert.match(readFileSync(join(appRoot, 'ui/admin/src/views/CatalogProductsView.vue'), 'utf8'), /人工业务扩展/u);
  assert.equal(JSON.parse(readFileSync(join(appRoot, 'evidence/regenerate.json'), 'utf8')).status, 0);
  assert.equal(JSON.parse(readFileSync(join(appRoot, 'evidence/vue-conflict.json'), 'utf8')).status, 2);
}));
