<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\benchmarks\Full.NET.Benchmarks\Full.NET.Benchmarks.csproj" Aliases="kafkabenchmarks" />
    <ProjectReference Include="..\..\src\Tools\Full.NET.CodeGeneration.Cli\Full.NET.CodeGeneration.Cli.csproj" Aliases="codegencli" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Data.CodeGeneration\Full.NET.Data.CodeGeneration.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Data.Abstractions\Full.NET.Data.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Data.Dapper\Full.NET.Data.Dapper.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Data.MySql\Full.NET.Data.MySql.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Migrations.DbUp\Full.NET.Migrations.DbUp.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Messaging.Abstractions\Full.NET.Messaging.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Messaging.Kafka\Full.NET.Messaging.Kafka.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Modularity\Full.NET.Modularity.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Seeding.Dapper\Full.NET.Seeding.Dapper.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Serialization.MemoryPack\Full.NET.Serialization.MemoryPack.csproj" />
    <ProjectReference Include="..\..\src\Hosts\Full.NET.Host.Api\Full.NET.Host.Api.csproj" />
    <ProjectReference Include="..\..\src\Hosts\Full.NET.Host.Worker\Full.NET.Host.Worker.csproj" Aliases="workerhost" />
    <ProjectReference Include="..\..\src\Modules\Full.NET.Modules.Identity\Full.NET.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\src\Modules\Full.NET.Modules.CodeGeneration\Full.NET.Modules.CodeGeneration.csproj" />
    <ProjectReference Include="..\..\src\Modules\Full.NET.Modules.Document\Full.NET.Modules.Document.csproj" />
    <ProjectReference Include="..\..\src\Modules\Full.NET.Modules.Jobs\Full.NET.Modules.Jobs.csproj" />
    <ProjectReference Include="..\..\src\Modules\Full.NET.Modules.Messaging\Full.NET.Modules.Messaging.csproj" />
    <ProjectReference Include="..\..\src\Modules\Full.NET.Modules.SerialNumbers\Full.NET.Modules.SerialNumbers.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.MySql" />
    <PackageReference Include="Testcontainers.Kafka" />
    <PackageReference Include="Testcontainers.Redis" />
  </ItemGroup>
</Project>
