using System.Text.Json;
using System.Text.Json.Serialization;
using Full.NET.Abstractions.Results;
using Full.NET.Modules.Identity.Contracts;
using Full.NET.Modules.Tenancy.Contracts;
using Full.NET.Modules.Tenancy.Persistence;

namespace Full.NET.Modules.Tenancy.Serialization;

[JsonSourceGenerationOptions(JsonSerializerDefaults.Web)]
[JsonSerializable(typeof(TenantSummary))]
[JsonSerializable(typeof(PagedResult<TenantSummary>))]
[JsonSerializable(typeof(TenantContextSummary[]))]
[JsonSerializable(typeof(ChangeTenantContextRequest))]
[JsonSerializable(typeof(TenantContextTokenResponse))]
[JsonSerializable(typeof(ProvisionTenantRequest))]
[JsonSerializable(typeof(UpdateHostTenantRequest))]
[JsonSerializable(typeof(TenantCachePayload))]
[JsonSerializable(typeof(TenantResolutionCacheEntry))]
[JsonSerializable(typeof(AssignHostTenantPackageRequest))]
[JsonSerializable(typeof(HostTenantMembersPageResponse))]
[JsonSerializable(typeof(HostTenantAdministratorsPageResponse))]
[JsonSerializable(typeof(HostTenantMemberResponse))]
[JsonSerializable(typeof(TenantBrandingResponse))]
[JsonSerializable(typeof(TenantRuntimeBrandingResponse))]
[JsonSerializable(typeof(UpdateTenantBrandingRequest))]
[JsonSerializable(typeof(TenantPackageSummary))]
[JsonSerializable(typeof(PagedResult<TenantPackageSummary>))]
[JsonSerializable(typeof(CreateHostTenantPackageRequest))]
[JsonSerializable(typeof(UpdateHostTenantPackageRequest))]
[JsonSerializable(typeof(SuspendTenantRequest))]
[JsonSerializable(typeof(ReactivateTenantRequest))]
[JsonSerializable(typeof(CloseTenantRequest))]
[JsonSerializable(typeof(TransferTenantOwnershipRequest))]
[JsonSerializable(typeof(TenantEntitlementCatalogResponse))]
[JsonSerializable(typeof(TenantEntitlementCatalogResponse[]))]
[JsonSerializable(typeof(IReadOnlyList<TenantEntitlementCatalogResponse>))]
[JsonSerializable(typeof(TenantEntitlementBindingResponse))]
[JsonSerializable(typeof(TenantEntitlementBindingResponse[]))]
[JsonSerializable(typeof(IReadOnlyList<TenantEntitlementBindingResponse>))]
[JsonSerializable(typeof(CreateTenantEntitlementCatalogRequest))]
[JsonSerializable(typeof(CreateTenantEntitlementBindingRequest))]
[JsonSerializable(typeof(TenantEntitlementEnforcementResponse))]
[JsonSerializable(typeof(UpdateTenantEntitlementEnforcementRequest))]
[JsonSerializable(typeof(TenantSubscriptionResponse))]
[JsonSerializable(typeof(TenantSubscriptionResponse[]))]
[JsonSerializable(typeof(IReadOnlyList<TenantSubscriptionResponse>))]
[JsonSerializable(typeof(CreateTenantSubscriptionRequest))]
[JsonSerializable(typeof(CancelTenantSubscriptionRequest))]
[JsonSerializable(typeof(ReserveTenantQuotaRequest))]
[JsonSerializable(typeof(ReserveTenantQuotaResponse))]
[JsonSerializable(typeof(ConfirmTenantQuotaRequest))]
[JsonSerializable(typeof(ReleaseTenantQuotaRequest))]
[JsonSerializable(typeof(TenantQuotaMetricResponse))]
[JsonSerializable(typeof(TenantQuotaMetricResponse[]))]
[JsonSerializable(typeof(IReadOnlyList<TenantQuotaMetricResponse>))]
[JsonSerializable(typeof(UpsertTenantQuotaMetricRequest))]
[JsonSerializable(typeof(ReconcileTenantQuotaMetricIdsRequest))]
[JsonSerializable(typeof(ReconcileTenantQuotaMetricIdsResponse))]
internal partial class TenancyJsonSerializerContext : JsonSerializerContext;
