<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <NeutralLanguage>zh-CN</NeutralLanguage>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MQTTnet" />
    <ProjectReference Include="..\..\BuildingBlocks\Full.NET.Abstractions\Full.NET.Abstractions.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Full.NET.Data.Abstractions\Full.NET.Data.Abstractions.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Full.NET.Data.Dapper\Full.NET.Data.Dapper.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Full.NET.Hosting\Full.NET.Hosting.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Full.NET.Modularity\Full.NET.Modularity.csproj" />
    <ProjectReference Include="..\Full.NET.Modules.Identity.Contracts\Full.NET.Modules.Identity.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\MqttErrors.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>MqttErrors.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Resources\MqttErrors.en-US.resx">
      <DependentUpon>MqttErrors.resx</DependentUpon>
    </EmbeddedResource>
  </ItemGroup>

</Project>
