<Project Sdk="MSTest.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\benchmarks\Full.NET.Benchmarks\Full.NET.Benchmarks.csproj" />
    <ProjectReference Include="..\..\src\Composition\Full.NET.Composition\Full.NET.Composition.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Abstractions\Full.NET.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Caching.Fusion\Full.NET.Caching.Fusion.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Data.Abstractions\Full.NET.Data.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Data.Dapper\Full.NET.Data.Dapper.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Data.MySql\Full.NET.Data.MySql.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Data.CodeGeneration\Full.NET.Data.CodeGeneration.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Hosting\Full.NET.Hosting.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Localization\Full.NET.Localization.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Messaging.Abstractions\Full.NET.Messaging.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Modularity\Full.NET.Modularity.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Realtime.Abstractions\Full.NET.Realtime.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Realtime.SignalR\Full.NET.Realtime.SignalR.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Serialization.MessagePack\Full.NET.Serialization.MessagePack.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Seeding.Abstractions\Full.NET.Seeding.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Seeding.Dapper\Full.NET.Seeding.Dapper.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Validation.FluentValidation\Full.NET.Validation.FluentValidation.csproj" />
    <ProjectReference Include="..\..\src\Tools\Full.NET.CodeGeneration.Cli\Full.NET.CodeGeneration.Cli.csproj" />
    <ProjectReference Include="..\..\src\Hosts\Full.NET.Host.Migrator\Full.NET.Host.Migrator.csproj" />
    <ProjectReference Include="..\..\src\Hosts\Full.NET.Host.Worker\Full.NET.Host.Worker.csproj" />
    <ProjectReference Include="..\..\src\Modules\Full.NET.Modules.Tenancy\Full.NET.Modules.Tenancy.csproj" />
    <ProjectReference Include="..\..\src\Modules\Full.NET.Modules.Identity\Full.NET.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\src\Modules\Full.NET.Modules.CodeGeneration\Full.NET.Modules.CodeGeneration.csproj" />
    <ProjectReference Include="..\..\src\Modules\Full.NET.Modules.SerialNumbers\Full.NET.Modules.SerialNumbers.csproj" />
    <ProjectReference Include="..\..\src\Modules\Full.NET.Modules.Files\Full.NET.Modules.Files.csproj" />
    <ProjectReference Include="..\..\src\Modules\Full.NET.Modules.Notifications\Full.NET.Modules.Notifications.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>
</Project>
