<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NeutralLanguage>zh-CN</NeutralLanguage>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\BuildingBlocks\Full.NET.Abstractions\Full.NET.Abstractions.csproj" />
    <ProjectReference Include="..\Full.NET.Modules.Identity.Contracts\Full.NET.Modules.Identity.Contracts.csproj" />
  </ItemGroup>
</Project>
