<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Data.Abstractions\Full.NET.Data.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Data.MySql\Full.NET.Data.MySql.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Migrations.DbUp\Full.NET.Migrations.DbUp.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Messaging.Kafka\Full.NET.Messaging.Kafka.csproj" />
    <ProjectReference Include="..\..\src\BuildingBlocks\Full.NET.Serialization.MessagePack\Full.NET.Serialization.MessagePack.csproj" />
    <ProjectReference Include="..\..\src\Hosts\Full.NET.Host.Api\Full.NET.Host.Api.csproj" Aliases="apiHost" />
    <ProjectReference Include="..\..\src\Hosts\Full.NET.Host.Worker\Full.NET.Host.Worker.csproj" Aliases="workerhost" />
    <ProjectReference Include="..\..\src\Modules\Full.NET.Modules.Auditing\Full.NET.Modules.Auditing.csproj" />
    <ProjectReference Include="..\..\src\Modules\Full.NET.Modules.Identity.Contracts\Full.NET.Modules.Identity.Contracts.csproj" />
    <ProjectReference Include="..\..\src\Modules\Full.NET.Modules.Jobs\Full.NET.Modules.Jobs.csproj" />
    <ProjectReference Include="..\..\src\Modules\Full.NET.Modules.Tenancy\Full.NET.Modules.Tenancy.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="Docker.DotNet.Enhanced" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="MySqlConnector" />
    <PackageReference Include="Testcontainers.MsSql" />
    <PackageReference Include="Testcontainers.MySql" />
  </ItemGroup>
</Project>
