CREATE TABLE IF NOT EXISTS fn_identity_user_profile (
    UserId BINARY(16) NOT NULL COMMENT '用户标识',
    Nickname varchar(128) NULL COMMENT '昵称',
    PhoneNumber varchar(32) NULL COMMENT '手机号',
    Email varchar(256) NULL COMMENT 'Email',
    EmployeeNumber varchar(64) NULL COMMENT '工号',
    Gender varchar(16) NULL COMMENT '性别',
    JoinDateUtc date NULL COMMENT '入职时间(UTC)',
    SortOrder int NOT NULL DEFAULT 100 COMMENT '排序顺序',
    IdCardType varchar(32) NULL COMMENT '证件类型',
    IdCardNumber varchar(64) NULL COMMENT '证件号码',
    BirthDate date NULL COMMENT '出生日期',
    Ethnicity varchar(64) NULL COMMENT '民族',
    Address varchar(512) NULL COMMENT '地址',
    GraduatedSchool varchar(256) NULL COMMENT '毕业院校',
    EducationLevel varchar(64) NULL COMMENT '学历',
    PoliticalStatus varchar(64) NULL COMMENT '政治面貌',
    OfficePhone varchar(32) NULL COMMENT '办公电话',
    EmergencyContact varchar(128) NULL COMMENT '紧急联系人',
    EmergencyContactPhone varchar(32) NULL COMMENT '紧急联系人电话',
    EmergencyContactAddress varchar(512) NULL COMMENT '紧急联系人地址',
    Remark varchar(512) NULL COMMENT '备注',
    Version int NOT NULL DEFAULT 1 COMMENT '乐观并发版本号',
    CONSTRAINT PK_fn_identity_user_profile PRIMARY KEY (UserId),
    CONSTRAINT FK_fn_identity_user_profile_User
        FOREIGN KEY (UserId) REFERENCES fn_identity_user(Id)
) COMMENT='身份认证用户资料表' ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;