-- 212：Agent 持久运行、步骤、检查点与事件；expand-only，支持幂等重跑与租约 fencing。
CREATE TABLE IF NOT EXISTS fn_ai_agent_run (
        Id binary(16) NOT NULL COMMENT '逻辑主键',
        ScopeKey varchar(32) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '可信租户 UUID 或 host',
        TenantId binary(16) NULL COMMENT '租户标识',
        ActorUserId binary(16) NOT NULL COMMENT '发起用户',
        SessionId binary(16) NOT NULL COMMENT '绑定会话',
        ClientRequestId binary(16) NOT NULL COMMENT '客户端幂等键',
        RequestHash varchar(64) CHARACTER SET ascii COLLATE ascii_bin NOT NULL COMMENT '完整请求摘要',
        DefinitionKey varchar(64) NOT NULL COMMENT 'Agent 定义键',
        DefinitionVersion int NOT NULL COMMENT 'Agent 定义版本',
        AuthorizationBindingId binary(16) NOT NULL COMMENT '授权绑定标识',
        SecurityStamp varchar(64) NOT NULL COMMENT '冻结安全戳',
        ActorScope varchar(64) NOT NULL COMMENT '冻结 Actor 作用域',
        EffectiveScope varchar(64) NOT NULL COMMENT '冻结有效作用域',
        StatusKey varchar(32) NOT NULL COMMENT '运行状态',
        BudgetJson longtext NOT NULL COMMENT '冻结预算 JSON',
        DeadlineAtUtc datetime(6) NOT NULL COMMENT '运行截止 UTC',
        Version bigint NOT NULL COMMENT '乐观版本',
        LeaseOwner varchar(128) NULL COMMENT '租约持有者',
        LeaseEpoch bigint NOT NULL COMMENT '租约代次',
        LeaseExpiresAtUtc datetime(6) NULL COMMENT '租约到期 UTC',
        CreatedAtUtc datetime(6) NOT NULL COMMENT '创建 UTC',
        UpdatedAtUtc datetime(6) NOT NULL COMMENT '更新 UTC',
        CONSTRAINT PK_fn_ai_agent_run PRIMARY KEY (Id),
        UNIQUE KEY UX_fn_ai_agent_run_Client (ScopeKey, ActorUserId, ClientRequestId),
        KEY IX_fn_ai_agent_run_CreatedAt (CreatedAtUtc, Id),
        CONSTRAINT CK_fn_ai_agent_run_StatusKey CHECK (StatusKey IN (
            'queued', 'running', 'completed', 'awaiting_approval', 'authorization_required',
            'retry_scheduled', 'reconciliation_required', 'failed', 'cancelled', 'expired'))
) COMMENT='人工智能 Agent 持久运行表' ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS fn_ai_agent_step (
        Id binary(16) NOT NULL COMMENT '逻辑主键',
        RunId binary(16) NOT NULL COMMENT '所属运行',
        StepKey varchar(64) NOT NULL COMMENT '步骤键',
        Attempt int NOT NULL COMMENT '尝试序号',
        OperationId binary(16) NOT NULL COMMENT '操作幂等标识',
        StatusKey varchar(16) NOT NULL COMMENT '步骤状态',
        ModelConfigVersion int NULL COMMENT '模型配置版本',
        ToolVersion int NULL COMMENT '工具版本',
        PriceVersionId binary(16) NULL COMMENT '价格版本',
        InputTokens bigint NULL COMMENT '输入 Token',
        OutputTokens bigint NULL COMMENT '输出 Token',
        Cost decimal(20,8) NULL COMMENT '步骤费用',
        Currency varchar(3) NULL COMMENT '币种',
        TraceId varchar(32) NULL COMMENT '跟踪标识',
        ArgumentDigest varchar(64) NULL COMMENT '参数摘要',
        ErrorCode varchar(64) NULL COMMENT '错误码',
        CreatedAtUtc datetime(6) NOT NULL COMMENT '创建 UTC',
        UpdatedAtUtc datetime(6) NOT NULL COMMENT '更新 UTC',
        CONSTRAINT PK_fn_ai_agent_step PRIMARY KEY (Id),
        UNIQUE KEY UX_fn_ai_agent_step_Attempt (RunId, StepKey, Attempt),
        UNIQUE KEY UX_fn_ai_agent_step_Operation (OperationId),
        KEY IX_fn_ai_agent_step_CreatedAt (CreatedAtUtc, Id),
        CONSTRAINT CK_fn_ai_agent_step_StatusKey CHECK (StatusKey IN ('started', 'committed', 'failed'))
) COMMENT='人工智能 Agent 步骤表' ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS fn_ai_agent_checkpoint (
        Id binary(16) NOT NULL COMMENT '逻辑主键',
        RunId binary(16) NOT NULL COMMENT '所属运行',
        Sequence bigint NOT NULL COMMENT '检查点序号',
        FormatVersion int NOT NULL COMMENT '载荷格式版本',
        FrameworkVersion varchar(16) NOT NULL COMMENT '框架版本',
        DefinitionVersion int NOT NULL COMMENT '定义版本',
        PayloadProtected longtext NOT NULL COMMENT '受保护检查点载荷',
        Checksum varchar(64) NOT NULL COMMENT '载荷校验和',
        CreatedAtUtc datetime(6) NOT NULL COMMENT '创建 UTC',
        CONSTRAINT PK_fn_ai_agent_checkpoint PRIMARY KEY (Id),
        UNIQUE KEY UX_fn_ai_agent_checkpoint_Sequence (RunId, Sequence),
        KEY IX_fn_ai_agent_checkpoint_CreatedAt (CreatedAtUtc, Id)
) COMMENT='人工智能 Agent 检查点表' ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS fn_ai_agent_event (
        Id binary(16) NOT NULL COMMENT '逻辑主键',
        RunId binary(16) NOT NULL COMMENT '所属运行',
        Sequence bigint NOT NULL COMMENT '事件序号',
        EventType varchar(64) NOT NULL COMMENT '事件类型',
        PayloadVersion int NOT NULL COMMENT '载荷版本',
        Payload longtext NOT NULL COMMENT '受控事件载荷',
        CreatedAtUtc datetime(6) NOT NULL COMMENT '创建 UTC',
        CONSTRAINT PK_fn_ai_agent_event PRIMARY KEY (Id),
        UNIQUE KEY UX_fn_ai_agent_event_Sequence (RunId, Sequence),
        KEY IX_fn_ai_agent_event_CreatedAt (CreatedAtUtc, Id)
) COMMENT='人工智能 Agent 事件表' ENGINE=InnoDB;
