<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\BuildingBlocks\Full.NET.Modularity\Full.NET.Modularity.csproj" />
    <ProjectReference Include="..\..\Modules\Full.NET.Modules.Identity\Full.NET.Modules.Identity.csproj" />
    <ProjectReference Include="..\..\Modules\Full.NET.Modules.Tenancy\Full.NET.Modules.Tenancy.csproj" />
    <ProjectReference Include="..\..\Modules\Full.NET.Modules.Organization\Full.NET.Modules.Organization.csproj" />
    <ProjectReference Include="..\..\Modules\Full.NET.Modules.Settings\Full.NET.Modules.Settings.csproj" />
    <ProjectReference Include="..\..\Modules\Full.NET.Modules.Auditing\Full.NET.Modules.Auditing.csproj" />
    <ProjectReference Include="..\..\Modules\Full.NET.Modules.Files\Full.NET.Modules.Files.csproj" />
    <ProjectReference Include="..\..\Modules\Full.NET.Modules.Document\Full.NET.Modules.Document.csproj" />
    <ProjectReference Include="..\..\Modules\Full.NET.Modules.Notifications\Full.NET.Modules.Notifications.csproj" />
    <ProjectReference Include="..\..\Modules\Full.NET.Modules.Jobs\Full.NET.Modules.Jobs.csproj" />
    <ProjectReference Include="..\..\Modules\Full.NET.Modules.Messaging\Full.NET.Modules.Messaging.csproj" />
    <ProjectReference Include="..\..\Modules\Full.NET.Modules.CodeGeneration\Full.NET.Modules.CodeGeneration.csproj" />
    <ProjectReference Include="..\..\Modules\Full.NET.Modules.SerialNumbers\Full.NET.Modules.SerialNumbers.csproj" />
  </ItemGroup>
</Project>
