using Full.NET.Modules.Document.Contracts;
using Full.NET.Modules.Identity.Contracts;

namespace Full.NET.Modules.Document;

internal sealed class DocumentAuthorizationContributor : IAuthorizationCatalogContributor
{
    public AuthorizationModuleDefinition Module { get; } =
        new("document", "文档中心", 100);

    public IReadOnlyCollection<PermissionDefinition> Permissions { get; } =
    [
        new(HostDocumentPermissions.Read, "读取 Host 文档库", AuthorizationScope.Host),
        new(HostDocumentPermissions.Create, "创建 Host 文档", AuthorizationScope.Host),
        new(HostDocumentPermissions.Update, "更新 Host 文档元数据", AuthorizationScope.Host),
        new(HostDocumentPermissions.AddVersion, "上传 Host 文档新版本", AuthorizationScope.Host),
        new(HostDocumentPermissions.Download, "下载 Host 文档当前版本", AuthorizationScope.Host),
        new(HostDocumentPermissions.Delete, "删除 Host 文档", AuthorizationScope.Host),
        new(HostDocumentPermissions.Restore, "恢复 Host 文档", AuthorizationScope.Host),
        new(HostDocumentCategoryPermissions.Read, "读取 Host 文档分类", AuthorizationScope.Host),
        new(HostDocumentCategoryPermissions.Create, "创建 Host 文档分类", AuthorizationScope.Host),
        new(HostDocumentCategoryPermissions.Update, "更新 Host 文档分类", AuthorizationScope.Host),
        new(HostDocumentCategoryPermissions.Delete, "删除 Host 文档分类", AuthorizationScope.Host),
        new(HostDocumentTagPermissions.Read, "读取 Host 文档标签", AuthorizationScope.Host),
        new(HostDocumentTagPermissions.Create, "创建 Host 文档标签", AuthorizationScope.Host),
        new(HostDocumentTagPermissions.Update, "更新 Host 文档标签", AuthorizationScope.Host),
        new(HostDocumentTagPermissions.Delete, "删除 Host 文档标签", AuthorizationScope.Host),
        new(HostDocumentRecycleBinPermissions.Read, "读取 Host 回收站", AuthorizationScope.Host),
        new(HostDocumentRecycleBinPermissions.Restore, "恢复 Host 回收站文档", AuthorizationScope.Host),
        new(HostDocumentRecycleBinPermissions.Purge, "彻底删除 Host 回收站文档", AuthorizationScope.Host),
        new(HostDocumentPermissionManagementPermissions.Read, "读取 Host 文档权限", AuthorizationScope.Host),
        new(HostDocumentPermissionManagementPermissions.Manage, "管理 Host 文档权限", AuthorizationScope.Host),
        new(HostDocumentSharePermissions.Read, "读取 Host 文档分享", AuthorizationScope.Host),
        new(HostDocumentSharePermissions.Create, "创建 Host 文档分享", AuthorizationScope.Host),
        new(HostDocumentSharePermissions.UpdateStatus, "更新 Host 文档分享状态", AuthorizationScope.Host),
        new(HostDocumentStatisticsPermissions.Read, "读取 Host 文档统计", AuthorizationScope.Host),
    ];

    public IReadOnlyCollection<NavigationDefinition> Navigation { get; } =
    [
        new NavigationDefinition(
            "host-document-items",
            null,
            "host-document-items",
            "/document/host-items",
            "host-document-items",
            "Host 文档库",
            "Host Documents",
            "document",
            71,
            HostDocumentPermissions.Read),
        new NavigationDefinition(
            "document-categories",
            null,
            "document-categories",
            "/document/categories",
            "document-categories",
            "文档分类",
            "Document Categories",
            "collection",
            72,
            HostDocumentCategoryPermissions.Read),
        new NavigationDefinition(
            "document-tags",
            null,
            "document-tags",
            "/document/tags",
            "document-tags",
            "文档标签",
            "Document Tags",
            "price-tag",
            73,
            HostDocumentTagPermissions.Read),
        new NavigationDefinition(
            "document-recycle-bin",
            null,
            "document-recycle-bin",
            "/document/recycle-bin",
            "document-recycle-bin",
            "文档回收站",
            "Document Recycle Bin",
            "delete",
            74,
            HostDocumentRecycleBinPermissions.Read),
        new NavigationDefinition(
            "document-shares",
            null,
            "document-shares",
            "/document/shares",
            "document-shares",
            "文档分享",
            "Document Shares",
            "share",
            75,
            HostDocumentSharePermissions.Read),
        new NavigationDefinition(
            "document-statistics",
            null,
            "document-statistics",
            "/document/statistics",
            "document-statistics",
            "文档统计",
            "Document Statistics",
            "chart-bar",
            76,
            HostDocumentStatisticsPermissions.Read),
    ];

    public IReadOnlyCollection<AuthorizationActionDefinition> Actions { get; } =
    [
        new AuthorizationActionDefinition(
            "document.host_documents.create",
            "host-document-items",
            HostDocumentPermissions.Create,
            "创建文档",
            "create",
            10),
        new AuthorizationActionDefinition(
            "document.host_documents.update",
            "host-document-items",
            HostDocumentPermissions.Update,
            "编辑文档",
            "update",
            20),
        new AuthorizationActionDefinition(
            "document.host_documents.add_version",
            "host-document-items",
            HostDocumentPermissions.AddVersion,
            "上传新版本",
            "add_version",
            30),
        new AuthorizationActionDefinition(
            "document.host_documents.download",
            "host-document-items",
            HostDocumentPermissions.Download,
            "下载当前版本",
            "download",
            35),
        new AuthorizationActionDefinition(
            "document.host_documents.delete",
            "host-document-items",
            HostDocumentPermissions.Delete,
            "删除文档",
            "delete",
            40),
        new AuthorizationActionDefinition(
            "document.host_documents.restore",
            "host-document-items",
            HostDocumentPermissions.Restore,
            "恢复文档",
            "restore",
            50),
        new AuthorizationActionDefinition(
            "document.categories.create",
            "document-categories",
            HostDocumentCategoryPermissions.Create,
            "创建分类",
            "create",
            10),
        new AuthorizationActionDefinition(
            "document.categories.update",
            "document-categories",
            HostDocumentCategoryPermissions.Update,
            "编辑分类",
            "update",
            20),
        new AuthorizationActionDefinition(
            "document.categories.delete",
            "document-categories",
            HostDocumentCategoryPermissions.Delete,
            "删除分类",
            "delete",
            30),
        new AuthorizationActionDefinition(
            "document.tags.create",
            "document-tags",
            HostDocumentTagPermissions.Create,
            "创建标签",
            "create",
            10),
        new AuthorizationActionDefinition(
            "document.tags.update",
            "document-tags",
            HostDocumentTagPermissions.Update,
            "编辑标签",
            "update",
            20),
        new AuthorizationActionDefinition(
            "document.tags.delete",
            "document-tags",
            HostDocumentTagPermissions.Delete,
            "删除标签",
            "delete",
            30),
        new AuthorizationActionDefinition(
            "document.host_recycle_bin.restore",
            "document-recycle-bin",
            HostDocumentRecycleBinPermissions.Restore,
            "恢复文档",
            "restore",
            10),
        new AuthorizationActionDefinition(
            "document.host_recycle_bin.purge",
            "document-recycle-bin",
            HostDocumentRecycleBinPermissions.Purge,
            "彻底删除",
            "purge",
            20),
        new AuthorizationActionDefinition(
            "document.host_permissions.manage",
            "host-document-items",
            HostDocumentPermissionManagementPermissions.Manage,
            "管理权限",
            "manage_permissions",
            60),
        new AuthorizationActionDefinition(
            "document.host_shares.create",
            "document-shares",
            HostDocumentSharePermissions.Create,
            "创建分享",
            "create",
            10),
        new AuthorizationActionDefinition(
            "document.host_shares.update_status",
            "document-shares",
            HostDocumentSharePermissions.UpdateStatus,
            "启用/禁用",
            "update_status",
            20),
    ];
}
