<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <ProjectReference Include="..\..\Composition\Full.NET.Composition\Full.NET.Composition.csproj" />
    <ProjectReference Include="..\..\BuildingBlocks\Full.NET.Hosting.Migrator\Full.NET.Hosting.Migrator.csproj" />
  </ItemGroup>

</Project>
