using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Full.NET.Messaging.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class IntegrationEventHandlerRegistryGenerator : IIncrementalGenerator
{
    private const string AttributeMetadataName =
        "Full.NET.Messaging.Abstractions.IntegrationEventSubscriptionAttribute";

    private static readonly DiagnosticDescriptor DuplicateRoute = new(
        "FNMESSAGING001",
        "集成事件订阅路由重复",
        "路由 ({0}, {1}, {2}) 已由多个订阅声明",
        "Full.NET.Messaging",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor InvalidMetadata = new(
        "FNMESSAGING002",
        "集成事件订阅元数据无效",
        "订阅 '{0}' 的 ConsumerName、MessageType 或 SchemaVersion 不符合稳定机器码约束",
        "Full.NET.Messaging",
        DiagnosticSeverity.Error,
        isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var subscriptions = context.SyntaxProvider.ForAttributeWithMetadataName(
            AttributeMetadataName,
            static (node, _) => node is ClassDeclarationSyntax,
            static (attributeContext, _) => CreateSubscription(attributeContext));
        context.RegisterSourceOutput(
            subscriptions.Collect(),
            static (productionContext, items) => Generate(productionContext, items));
    }

    private static SubscriptionMetadata CreateSubscription(
        GeneratorAttributeSyntaxContext context)
    {
        var type = (INamedTypeSymbol)context.TargetSymbol;
        var attribute = context.Attributes[0];
        return new SubscriptionMetadata(
            type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
            attribute.ConstructorArguments[0].Value as string ?? string.Empty,
            attribute.ConstructorArguments[1].Value as string ?? string.Empty,
            attribute.ConstructorArguments[2].Value is int version ? version : 0,
            type.Locations.FirstOrDefault());
    }

    private static void Generate(
        SourceProductionContext context,
        ImmutableArray<SubscriptionMetadata> items)
    {
        var valid = new List<SubscriptionMetadata>(items.Length);
        foreach (var item in items)
        {
            if (!IsValidConsumerName(item.ConsumerName)
                || !IsValidMessageType(item.MessageType)
                || item.SchemaVersion < 1)
            {
                context.ReportDiagnostic(Diagnostic.Create(
                    InvalidMetadata,
                    item.Location,
                    item.TypeName));
                continue;
            }

            valid.Add(item);
        }

        var ordered = valid
            .OrderBy(item => item.MessageType, StringComparer.Ordinal)
            .ThenBy(item => item.SchemaVersion)
            .ThenBy(item => item.ConsumerName, StringComparer.Ordinal)
            .ThenBy(item => item.TypeName, StringComparer.Ordinal)
            .ToArray();
        foreach (var group in ordered.GroupBy(
                     item => new RouteKey(
                         item.MessageType,
                         item.SchemaVersion,
                         item.ConsumerName)))
        {
            if (group.Skip(1).Any())
            {
                var first = group.First();
                context.ReportDiagnostic(Diagnostic.Create(
                    DuplicateRoute,
                    first.Location,
                    first.MessageType,
                    first.SchemaVersion,
                    first.ConsumerName));
            }
        }

        var unique = ordered
            .GroupBy(item => new RouteKey(
                item.MessageType,
                item.SchemaVersion,
                item.ConsumerName))
            .Select(group => group.First())
            .ToArray();
        context.AddSource(
            "IntegrationEventHandlerRegistry.g.cs",
            SourceText.From(Render(unique), Encoding.UTF8));
    }

    private static string Render(IReadOnlyList<SubscriptionMetadata> items)
    {
        var source = new StringBuilder(
            """
            // <auto-generated />
            #nullable enable
            namespace Full.NET.Generated;

            internal sealed class IntegrationEventHandlerRegistry
                : global::Full.NET.Messaging.Abstractions.IIntegrationEventHandlerRegistry
            {
                public bool TryResolve(
                    string messageType,
                    int schemaVersion,
                    string consumerName,
                    out global::Full.NET.Messaging.Abstractions.IntegrationEventHandlerDescriptor descriptor)
                {
                    switch ((messageType, schemaVersion, consumerName))
                    {
            """);
        foreach (var item in items)
        {
            source.Append("            case (")
                .Append(SymbolDisplay.FormatLiteral(item.MessageType, quote: true))
                .Append(", ")
                .Append(item.SchemaVersion)
                .Append(", ")
                .Append(SymbolDisplay.FormatLiteral(item.ConsumerName, quote: true))
                .AppendLine("):" )
                .Append("                descriptor = new(")
                .Append(SymbolDisplay.FormatLiteral(item.MessageType, quote: true))
                .Append(", ")
                .Append(item.SchemaVersion)
                .Append(", ")
                .Append(SymbolDisplay.FormatLiteral(item.ConsumerName, quote: true))
                .Append(", typeof(")
                .Append(item.TypeName)
                .AppendLine("));")
                .AppendLine("                return true;");
        }

        source.Append(
            """
                        default:
                            descriptor = default;
                            return false;
                    }
                }
            }
            """);
        return source.ToString();
    }

    private static bool IsValidConsumerName(string value) =>
        value.Length is > 0 and <= 128
        && IsDotSeparatedMachineCode(
            value,
            minimumSegments: 1,
            allowUnderscore: true,
            allowHyphen: true);

    private static bool IsValidMessageType(string value) =>
        value.Length is > 0 and <= 256
        && IsDotSeparatedMachineCode(
            value,
            minimumSegments: 4,
            allowUnderscore: true,
            allowHyphen: false);

    private static bool IsDotSeparatedMachineCode(
        string value,
        int minimumSegments,
        bool allowUnderscore,
        bool allowHyphen)
    {
        var segments = value.Split('.');
        if (segments.Length < minimumSegments)
        {
            return false;
        }

        foreach (var segment in segments)
        {
            if (segment.Length == 0 || segment[0] is < 'a' or > 'z')
            {
                return false;
            }

            for (var index = 1; index < segment.Length; index++)
            {
                var character = segment[index];
                if (character is >= 'a' and <= 'z'
                    || character is >= '0' and <= '9'
                    || allowUnderscore && character == '_'
                    || allowHyphen && character == '-')
                {
                    continue;
                }

                return false;
            }
        }

        return true;
    }

    private sealed class SubscriptionMetadata(
        string typeName,
        string consumerName,
        string messageType,
        int schemaVersion,
        Location? location)
    {
        public string TypeName { get; } = typeName;

        public string ConsumerName { get; } = consumerName;

        public string MessageType { get; } = messageType;

        public int SchemaVersion { get; } = schemaVersion;

        public Location? Location { get; } = location;
    }

    private sealed class RouteKey(
        string messageType,
        int schemaVersion,
        string consumerName) : IEquatable<RouteKey>
    {
        private readonly string _messageType = messageType;
        private readonly int _schemaVersion = schemaVersion;
        private readonly string _consumerName = consumerName;

        public bool Equals(RouteKey? other) =>
            other is not null
            && _schemaVersion == other._schemaVersion
            && string.Equals(_messageType, other._messageType, StringComparison.Ordinal)
            && string.Equals(_consumerName, other._consumerName, StringComparison.Ordinal);

        public override bool Equals(object? obj) => Equals(obj as RouteKey);

        public override int GetHashCode()
        {
            unchecked
            {
                var hash = StringComparer.Ordinal.GetHashCode(_messageType);
                hash = (hash * 397) ^ _schemaVersion;
                hash = (hash * 397) ^ StringComparer.Ordinal.GetHashCode(_consumerName);
                return hash;
            }
        }
    }
}
