#if FULLNET_AOT_COMPILE
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Full.NET.Modules.Identity")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Full.NET.Modules.Tenancy")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Full.NET.Modules.Organization")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Full.NET.Modules.CodeGeneration")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Full.NET.Modules.Files")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Full.NET.Modules.Notifications")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Full.NET.Modules.Messaging")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Full.NET.Modules.Settings")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Full.NET.Modules.Jobs")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Full.NET.Modules.SerialNumbers")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Full.NET.Modules.Document")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Full.NET.Modules.Auditing")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Full.NET.Modules.Workflow")]
#endif
