<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Full.NET.Abstractions\Full.NET.Abstractions.csproj" />
    <ProjectReference Include="..\Full.NET.Data.Abstractions\Full.NET.Data.Abstractions.csproj" />
    <ProjectReference Include="..\Full.NET.Data.MySql\Full.NET.Data.MySql.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Dapper" />
    <PackageReference Include="Dapper.AOT" GeneratePathProperty="true" />
    <PackageReference Include="Microsoft.Data.SqlClient" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
  </ItemGroup>
  <ItemGroup>
    <Analyzer
      Include="$(PkgDapper_AOT)/analyzers/dotnet/Dapper.AOT.Analyzers.dll"
      Condition="'$(PkgDapper_AOT)' != ''" />
  </ItemGroup>
  <ItemGroup Condition="'$(FullNetIsAotCompile)' == 'true'">
    <RuntimeHostConfigurationOption
      Include="Microsoft.Data.SqlClient.EnableReflectionBasedAuthenticationProviderDiscovery"
      Value="false"
      Trim="true" />
  </ItemGroup>

</Project>
